[package]
name = "rpl_doc"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
pest.workspace = true
rpl_parser.workspace = true
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tempfile = "3"

[lib]
doctest = false

[package.metadata.rust-analyzer]
# This crate transitively uses #[feature(rustc_private)] via rpl_parser
rustc_private = true
