[package]
name = "rpl_doc"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
thiserror.workspace = true
walkdir.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lib]
doctest = false
